name: axios
description: Simple, zero-configuration command-line http server
version: 1.0.0
repository: https://github.com/Sayegh7/axios

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http_server: ^0.9.8+3
  args: ^2.0.0
  ansicolor: ^1.1.1
